### ISSUE TITLE
v1.1 roadmap

### ISSUE THREAD

**Issue by gboeing** [gboeing/osmnx#655]
Work to complete prior to v1.1.0 release, targeted for early May 2021:
  - [x] improve `save_graph_xml` speed (#646)
  - [x] use integer node IDs in `consolidate_intersections` (#647)
  - [x] fix `network_type` filters allowing ways tagged "bus_guideway" (#661)
  - [x] fix `truncate_graph_dist` retaining unreachable nodes (#651)
  - [x] add option to return distances in `get_nearest_nodes` (#650)
  - [x] handle relations of type "boundary" in `geometries` module (#654)
  - [x] multi-index GeoDataFrames returned from `geometries` module by element type and osmid (#654)
  - [x] clearer geocoder error messages (#668)
  - [x] remove `descartes` dependency because GeoPandas has removed it (#669)
  - [x] handle boolean attribute type conversion when loading GraphML files (#665)
  - [x] clearer handling of node geometry in `graph_from_gdfs` (#678)
  - [x] fix stack overflow bug in performing shapely unary_union on pygeos geometries (#679)
  - [x] add graph-constrained random spatial sampling feature (#639)
  - [x] refactor `stats` module (#674)
  - [x] refactor `distance` module (#675)
  - [x] fix new dependency versions' warnings and improve test coverage (#688)
  - [x] vectorize add_edge_lengths and add_edge_grades functions; move add_edge_lengths to distance module (#692)
  - [x] add add_node_elevations_raster function and add_node_elevations_google function (#690)

See the [change log](https://github.com/gboeing/osmnx/blob/main/CHANGELOG.md) for more details.

**Comment by gboeing** [comment]
I'm looking for anyone interested in testing any of these new features. If anything here looks interesting/useful to you, you can install the current main branch with `pip install git+git://github.com/gboeing/osmnx.git` and try them out. The [latest](https://osmnx.readthedocs.io/en/latest/) documentation tracks this pre-release's functionality. Your feedback is appreciated as we prepare for release.

**Comment by renardgris30** [comment]
I'm a french student and i'm really interest to test it and especialy (#690) but got the error. Please help. Thank you
pip install https://github.com/gboeing/osmnx.git
Collecting https://github.com/gboeing/osmnx.git
Downloading https://github.com/gboeing/osmnx.git
ERROR: Cannot unpack file C:\Users\PBENEZ~1\AppData\Local\Temp\pip-unpack-p7r1u6qs\osmnx.git (downloaded from C:\Users\PBENEZ~1\AppData\Local\Temp\pip-req-build-ghvg47tk, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\PBENEZ~1\AppData\Local\Temp\pip-req-build-ghvg47tk

**Comment by gboeing** [comment]
@renardgris30 it looks like this may be answered here: https://stackoverflow.com/questions/20950295/pip-install-error-unknown-archive-format-whl

**Comment by NicMan89** [comment]
@gboeing  Thanks a lot for your efforts e your project. I installed the main branch with pip and (#647 ) now work for me.

**Comment by renardgris30** [comment]
@gboeing : Got it ! Issue fixed adding PYTHONUTF8=1 in SHELL environment

**Comment by renardgris30** [comment]
@gboeing : Trying to convert CRS EPSG:3395 to EPSG:4326 with following code but do not convert. Thank you

import osmnx as ox
G=ox.graph_from_bbox(43.808969,43.79,4.087298,4.1,network_type='drive',simplify=True,truncate_by_edge=True,clean_periphery=True)
G_projected1 = ox.projection.project_graph(G)
crs=ox.projection.is_projected('EPSG:3395')
print('crs EPSG:3395 ? ',crs)
>>> crs EPSG:3395 ? True
G_projected2 = ox.projection.project_graph(G_projected1, to_crs='EPSG:4326')
crs=ox.projection.is_projected('EPSG:3395')
print('crs EPSG:3395 ?',crs)
>>> crs EPSG:3395 ? True

**Comment by renardgris30** [comment]
@gboeing : sorry better to check before sending with Preview

G = ox.graph_from_bbox(43.808969,43.79,4.087298,4.1, network_type='drive',simplify=True,truncate_by_edge=True,clean_periphery=True)

G_projected1 = ox.projection.project_graph(G)
crs=ox.projection.is_projected('EPSG:3395')
print('crs EPSG:3395 ? ',crs)

G_projected2 = ox.projection.project_graph(G_projected1, to_crs='EPSG:4326')
crs=ox.projection.is_projected('EPSG:3395')
print('crs EPSG:3395 ?',crs)

**Comment by gboeing** [comment]
Hi @renardgris30, I'm not clear exactly what you're trying to do in that code (or what error you're getting), but it looks like you're not using the `project_graph` function properly. See [the docs](https://osmnx.readthedocs.io/en/latest/osmnx.html#module-osmnx.projection) for usage, and you can ask on StackOverflow if you have a usage question about it.

**Comment by gboeing** [comment]
v1.1.0 has been released.
